# Generated by Django 4.1.2 on 2023-06-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('imagen_producto', models.ImageField(null=True, upload_to='noticias')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_noticia',
            fields=[
                ('id_tipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('nombre_tipo_noticia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(db_column='idNoticia', primary_key=True, serialize=False)),
                ('titular', models.CharField(max_length=500)),
                ('subtitulo', models.CharField(max_length=500)),
                ('entradilla', models.CharField(max_length=5000)),
                ('cuerpo_noticia', models.CharField(max_length=10000)),
                ('fecha_noticia', models.DateField()),
                ('imagen_noticia', models.ImageField(null=True, upload_to='noticias')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='noticias.tipo_noticia')),
            ],
        ),
    ]
