# Generated by Django 4.1.2 on 2023-06-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_noticia',
            name='num_subtipo_noticia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
