# Generated by Django 4.1.2 on 2023-07-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_remove_tipo_noticia_num_subtipo_noticia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='idNoticia', primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=500)),
                ('correo_electronico', models.CharField(max_length=500)),
                ('nombre_usuario', models.CharField(max_length=500)),
                ('contrasenna', models.CharField(max_length=500)),
            ],
        ),
    ]
